version: "3.9"

services:
  app:
    build: .
    container_name: chatapp
    ports:
      - "1002:1002"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/chatapp
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
